FROM node:4.3.2
ADD package.json /src/package.json
RUN cd /src && npm install
ADD . /src
WORKDIR /src

ENV PARSE_DASHBOARD_SERVER_URL https://api.parse.com/1
ENV PARSE_DASHBOARD_MASTER_KEY BqhfEsnYq6ODxyHnO4iGqga8owlO4gUn356wiej9
ENV PARSE_DASHBOARD_APP_ID G7bZDYGQRiUvcscDjD1mtKLPqRAxcv4kkNJTWqbk
ENV PARSE_DASHBOARD_APP_NAME PhysioApp on Parse.com
ENV PARSE_JS_KEY mIvmhgPW5UUoGMuIqNi0WZuwTGwKZxBFUhEQQ37J
ENV PARSE_REST_KEY 2tOJpoL4ELtDbVric3DgDdZGYFGUU9Dv22dVcyNa
ENV PARSE_DASHBOARD_ALLOW_INSECURE_HTTP true
ENV PARSE_DASHBOARD_USER_ID setUserID
ENV PARSE_DASHBOARD_USER_PASSWORD setPassword

ENTRYPOINT ["npm", "run", "dashboard"]
